#!/bin/bash


# check if we're in an interactive shell
if [ -z "$PS1" ]
then

  branch="$(git rev-parse --abbrev-ref HEAD)"
  if [ "$branch" = "master" ] || [ "$branch" = "main" ]
  then

    read -p "Really commit to $branch? [yN] "
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      exit 0
    else
      echo "Canceled by user."
    fi
  fi
fi
